### PR TITLE
Moved FTRIM into Calibration function and included it in the readme.md.

### PR DESCRIPTION
**Pull request by ntodzy**
subject

### CODE REVIEW

**Comment by felixge** [comment]
@Skyguy92 thx. What's the motivation for this change?

**Comment by Skyguy92** [comment]
@felixge Hey! Recently my friends and I had the privilege to go through a bunch of old technology at our local high school. We ended up finding a bunch of repair kits, spare drives, 4 working drones, and 1 with a wrecked prop. So we wrote some scripts to control the drone with my euphonium... and the drone we were using the gyro was offset, so we needed to calibrate it, so after digging through the client.js and finding ftrim we used that and it started working okay. Great! So then I remembered it was hacktober and decided to add some documentation for ftrim by moving it under the calibration category. Sooo. that's what I did.

**Comment by felixge** [comment]
@Skyguy92 ok, makes sense.

**Comment by felixge** [comment]
Sorry for the delay to merge this : )

**Pull request merged**
